### PR TITLE
Markdown content in Spanish and Catalan

### PR DESCRIPTION
**Pull request by rewritten**
Bonus: jekyll goodies

### CODE REVIEW

**Comment by rewritten** [comment]
@enricostano this one

**Comment by enricostano** [comment]
We still need to understand what `coopdevs.org/` should show by default. I understand that the current `index.html` should be removed and maybe a default locale should be shown, `/es` for instance.

How? Any thought @rewritten ?

EDIT: right now, with this PR, going to `/` shows a broken `index.html`, that we should remove or change in some way

**Comment by enricostano** [comment]
Maybe @fcsonline can shade some light on this :wink:

**Comment by rewritten** [comment]
I'll check about a redirect. Just for this to be mergeable.

**Comment by fcsonline** [comment]
You can do a redirect depending on the `Accept-Language` header. To do that you need some dynamic software to manage it. There are two solutions:
- Some small app (node, ruby) to read the header and do the redirect (Hard way)
- A Nginx redirect with a `rewrite` rule. (Easier way) [Example](http://stackoverflow.com/questions/3657614/how-to-rewrite-location-in-nginx-depending-on-the-client-browsers-language)

**Comment by enricostano** [comment]
@fcsonline the problem here is that we host this on GitHub Pages :grimacing:

**Comment by rewritten** [comment]
``` yml
---
refresh:
  timeout: 10
  url: /relative-link.html
---
```

will add a refresh tag in the head and a message in the body. Is it enough?

**Comment by enricostano** [comment]
Maybe we just need to play with the `permalink` header for the default language... or host this on some nginx. :sob:

**Comment by enricostano** [comment]
https://github.com/untra/polyglot may be useful

Still no clue on how to keep using GH pages with a translated site.

**Comment by rewritten** [comment]
Polyglot is beautiful. We need to go out from GH pages.

By the way, polyglot features are slightly right-wing:

> (http://untra.github.io/polyglot/es/)
>    Polyglot se encarga de las tonterías típicas normalmente de izquierda a los desarrolladores 

:joy: :joy: :joy: :joy: :joy:

**Comment by enricostano** [comment]
LOOOL :-1:

**Comment by naoisegolden** [comment]
@rewritten @enricostano what's pending for this PR? Can I help so we can move on with #1 ?

**Comment by enricostano** [comment]
@naoisegolden I'm going to buy a new cheap VPS to host both this and a [Discourse](http://www.discourse.org/) instance. In this way we can:
1. use all the Jekyll plugins we want for this repo
2. let NGINX manage the default URL
3. try out Discourse for internal communication

**Comment by enricostano** [comment]
Now that we merged https://github.com/coopdevs/coopdevs-provisioning/pull/4 we can move forward and merge this one too **once we completely move from GH pages to out own VPS**. Thing that should happen during this month.

**Comment by enricostano** [comment]
Closing since we switched to new implementation: https://github.com/coopdevs/coopdevs.github.io

**Pull request closed without merging**
